'use strict'

const { GoogleGenerativeAI } = require('@google/generative-ai')

const MODEL = "gemini-3-flash-preview";
const MAX_TOKENS  = 8192
const TEMPERATURE = 0.4

const buildPrompt = (transcript, meta) => `
You are an expert knowledge architect. Convert this YouTube transcript into a SKILL.md file.

A SKILL.md is NOT a summary. It is an interactive agent script.
When a user pastes it into any AI agent and says "execute this skill", the agent must:
1. Ask the user targeted questions ONE AT A TIME to understand their situation
2. Apply the speaker's exact framework to their specific answers
3. Produce a fully personalized action plan — not generic advice

VIDEO METADATA:
Title: ${meta.title || 'Unknown'}
Video ID: ${meta.videoId}

TRANSCRIPT:
${transcript}

Produce the SKILL.md using EXACTLY this format. Never use placeholders — extract real content from the transcript.

# SKILL: [specific topic from transcript]
**Source:** [speaker name and credential]
**Expertise:** [what they built — use their exact numbers]
**Topic:** [one sentence]
**Use when:** [specific trigger situation]

---

## AGENT INSTRUCTIONS

You are acting as [speaker name]'s personal advisor.

Before giving advice, ask these questions ONE AT A TIME:

### Question Sequence

[4-6 specific questions tied directly to decision points in the speaker's framework]
**Q[n]:** "[question]"

Once you have all answers, apply the framework immediately.

---

## EXECUTION FRAMEWORK

[Speaker's complete methodology — phases, numbered steps, exact tools, exact numbers]

---

## PERSONALIZATION LAYER

Using the user's answers, customize each phase:
- If user answered Q[n] with [type of answer] → [how advice changes]

---

## DECISION POINTS

- IF [condition] → [action]
[minimum 5]

---

## WHAT NOT TO DO

[Speaker's explicit warnings — use their exact language]

---

## SPEAKER'S MENTAL MODELS

[4-6 core thinking frameworks the speaker uses]

---

## EXPECTED OUTCOMES

[Specific results, numbers, timelines the speaker mentioned — exact, not approximate]

---

## OUTPUT FORMAT

After collecting answers, always respond with:
### 1. Your Situation Assessment
### 2. Your Personalized [Phase name]
[one section per phase]
### 3. Your [timeframe] Action Plan
### 4. Your First Action (next 24 hours)

---

## SPEAKER'S KEY PRINCIPLES

[3-5 quotes or close paraphrases capturing core philosophy]

---
*Generated by SkillDrop from: ${meta.title || meta.videoId}*
*youtube.com/watch?v=${meta.videoId}*
`.trim()

let _client = null

const getClient = () => {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('[SkillService] GEMINI_API_KEY is not set')
  }
  if (!_client) _client = new GoogleGenerativeAI(process.env.GEMINI_API_KEY)
  return _client
}

const generateSkill = async (transcript, meta) => {
  console.log(`[SkillService] Generating SKILL.md — ${meta.title || meta.videoId}`)

  if (!transcript?.trim()) {
    throw new Error('[SkillService] Transcript is empty')
  }

  const model = getClient().getGenerativeModel({
    model: MODEL,
    generationConfig: { maxOutputTokens: MAX_TOKENS, temperature: TEMPERATURE },
  })

  let result
  try {
    result = await model.generateContent(buildPrompt(transcript, meta))
  } catch (err) {
    throw new Error(`[SkillService] Gemini call failed: ${err.message}`)
  }

  const skillMd = result?.response?.text()
  if (!skillMd?.trim()) throw new Error('[SkillService] Gemini returned empty content')

  console.log(`[SkillService] Done — ${skillMd.length} chars`)
  return skillMd
}

module.exports = { generateSkill }
